<?php
/**
 * GeoPortfolio Pro - Installation Script
 * This script will help you install the GeoPortfolio Pro system
 */

// Prevent running if already installed
if (file_exists('config/installed.lock')) {
    die('Installation already completed. Delete config/installed.lock to reinstall.');
}

$step = isset($_GET['step']) ? intval($_GET['step']) : 1;
$error = '';
$success = '';

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($step) {
        case 1: // Database Configuration
            $dbHost = trim($_POST['db_host']);
            $dbName = trim($_POST['db_name']);
            $dbUser = trim($_POST['db_user']);
            $dbPass = $_POST['db_pass'];
            
            // Test database connection
            try {
                $pdo = new PDO("mysql:host=$dbHost", $dbUser, $dbPass);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                
                // Create database if it doesn't exist
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `$dbName`");
                
                // Save database config
                $configContent = "<?php
/**
 * Database Configuration
 * Generated by GeoPortfolio Pro Installer
 */

class Database {
    private \$host = '$dbHost';
    private \$database = '$dbName';
    private \$username = '$dbUser';
    private \$password = '$dbPass';
    private \$charset = 'utf8mb4';
    private \$pdo;

    public function __construct() {
        \$dsn = \"mysql:host={\$this->host};dbname={\$this->database};charset={\$this->charset}\";
        \$options = [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ];

        try {
            \$this->pdo = new PDO(\$dsn, \$this->username, \$this->password, \$options);
        } catch (PDOException \$e) {
            throw new PDOException(\$e->getMessage(), (int)\$e->getCode());
        }
    }

    public function getConnection() {
        return \$this->pdo;
    }
}

function getDB() {
    static \$db = null;
    if (\$db === null) {
        \$database = new Database();
        \$db = \$database->getConnection();
    }
    return \$db;
}
?>";
                
                file_put_contents('config/database.php', $configContent);
                
                // Store config in session for next step
                session_start();
                $_SESSION['install_config'] = [
                    'db_host' => $dbHost,
                    'db_name' => $dbName,
                    'db_user' => $dbUser,
                    'db_pass' => $dbPass
                ];
                
                header('Location: install.php?step=2');
                exit;
                
            } catch (PDOException $e) {
                $error = 'Database connection failed: ' . $e->getMessage();
            }
            break;
            
        case 2: // Import Database Schema
            session_start();
            if (!isset($_SESSION['install_config'])) {
                header('Location: install.php?step=1');
                exit;
            }
            
            try {
                require_once 'config/database.php';
                $db = getDB();
                
                // Read and execute schema
                $schema = file_get_contents('sql/database_schema.sql');
                $statements = explode(';', $schema);
                
                foreach ($statements as $statement) {
                    $statement = trim($statement);
                    if (!empty($statement)) {
                        $db->exec($statement);
                    }
                }
                
                // Import sample data if requested
                if (isset($_POST['import_sample_data'])) {
                    $sampleData = file_get_contents('sql/sample_data.sql');
                    $statements = explode(';', $sampleData);
                    
                    foreach ($statements as $statement) {
                        $statement = trim($statement);
                        if (!empty($statement)) {
                            $db->exec($statement);
                        }
                    }
                }
                
                header('Location: install.php?step=3');
                exit;
                
            } catch (Exception $e) {
                $error = 'Database import failed: ' . $e->getMessage();
            }
            break;
            
        case 3: // Create Admin User
            session_start();
            if (!isset($_SESSION['install_config'])) {
                header('Location: install.php?step=1');
                exit;
            }
            
            $adminName = trim($_POST['admin_name']);
            $adminEmail = trim($_POST['admin_email']);
            $adminPassword = $_POST['admin_password'];
            $confirmPassword = $_POST['confirm_password'];
            
            if (empty($adminName) || empty($adminEmail) || empty($adminPassword)) {
                $error = 'All fields are required.';
            } elseif (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
                $error = 'Invalid email address.';
            } elseif (strlen($adminPassword) < 6) {
                $error = 'Password must be at least 6 characters long.';
            } elseif ($adminPassword !== $confirmPassword) {
                $error = 'Passwords do not match.';
            } else {
                try {
                    require_once 'config/database.php';
                    $db = getDB();
                    
                    // Check if admin user already exists
                    $stmt = $db->prepare("SELECT id FROM users WHERE email = ? OR role = 'admin'");
                    $stmt->execute([$adminEmail]);
                    
                    if ($stmt->fetch()) {
                        $error = 'Admin user already exists.';
                    } else {
                        // Create admin user
                        $hashedPassword = password_hash($adminPassword, PASSWORD_DEFAULT);
                        $stmt = $db->prepare("INSERT INTO users (name, email, password, role, is_active, created_at) VALUES (?, ?, ?, 'admin', 1, NOW())");
                        $stmt->execute([$adminName, $adminEmail, $hashedPassword]);
                        
                        header('Location: install.php?step=4');
                        exit;
                    }
                } catch (Exception $e) {
                    $error = 'Failed to create admin user: ' . $e->getMessage();
                }
            }
            break;
            
        case 4: // Final Configuration
            session_start();
            if (!isset($_SESSION['install_config'])) {
                header('Location: install.php?step=1');
                exit;
            }
            
            try {
                require_once 'config/database.php';
                $db = getDB();
                
                // Save basic site settings
                $settings = [
                    'site_title' => trim($_POST['site_title']) ?: 'GeoPortfolio Pro',
                    'site_description' => trim($_POST['site_description']) ?: 'A modern portfolio for GIS & Remote Sensing professionals',
                    'copyright_text' => trim($_POST['copyright_text']) ?: 'GeoPortfolio Pro. All rights reserved.'
                ];
                
                foreach ($settings as $key => $value) {
                    $stmt = $db->prepare("INSERT INTO site_settings (setting_key, setting_value) VALUES (?, ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
                    $stmt->execute([$key, $value]);
                }
                
                // Create installation lock file
                file_put_contents('config/installed.lock', date('Y-m-d H:i:s'));
                
                // Clear session
                unset($_SESSION['install_config']);
                
                header('Location: install.php?step=5');
                exit;
                
            } catch (Exception $e) {
                $error = 'Failed to save configuration: ' . $e->getMessage();
            }
            break;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GeoPortfolio Pro - Installation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            font-family: 'Inter', sans-serif;
        }
        .install-container {
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            overflow: hidden;
            max-width: 600px;
            margin: 2rem auto;
        }
        .install-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            text-align: center;
        }
        .step-indicator {
            display: flex;
            justify-content: center;
            margin-bottom: 2rem;
        }
        .step {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 0.5rem;
            font-weight: bold;
        }
        .step.active {
            background: #667eea;
            color: white;
        }
        .step.completed {
            background: #28a745;
            color: white;
        }
        .step.pending {
            background: #e9ecef;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="container py-4">
        <div class="install-container">
            <div class="install-header">
                <i class="fas fa-globe fa-3x mb-3"></i>
                <h1>GeoPortfolio Pro</h1>
                <p class="mb-0">Installation Wizard</p>
            </div>
            
            <div class="p-4">
                <!-- Step Indicator -->
                <div class="step-indicator">
                    <?php for ($i = 1; $i <= 5; $i++): ?>
                        <div class="step <?php 
                            if ($i < $step) echo 'completed';
                            elseif ($i == $step) echo 'active';
                            else echo 'pending';
                        ?>">
                            <?php if ($i < $step): ?>
                                <i class="fas fa-check"></i>
                            <?php else: ?>
                                <?php echo $i; ?>
                            <?php endif; ?>
                        </div>
                    <?php endfor; ?>
                </div>

                <?php if ($error): ?>
                    <div class="alert alert-danger">
                        <i class="fas fa-exclamation-triangle me-2"></i>
                        <?php echo htmlspecialchars($error); ?>
                    </div>
                <?php endif; ?>

                <?php if ($success): ?>
                    <div class="alert alert-success">
                        <i class="fas fa-check-circle me-2"></i>
                        <?php echo htmlspecialchars($success); ?>
                    </div>
                <?php endif; ?>

                <?php if ($step == 1): ?>
                    <!-- Step 1: Database Configuration -->
                    <h3><i class="fas fa-database me-2"></i>Database Configuration</h3>
                    <p class="text-muted mb-4">Enter your database connection details.</p>
                    
                    <form method="POST">
                        <div class="mb-3">
                            <label for="db_host" class="form-label">Database Host</label>
                            <input type="text" class="form-control" id="db_host" name="db_host" 
                                   value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="db_name" class="form-label">Database Name</label>
                            <input type="text" class="form-control" id="db_name" name="db_name" 
                                   value="<?php echo htmlspecialchars($_POST['db_name'] ?? 'geoportfolio_pro'); ?>" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="db_user" class="form-label">Database Username</label>
                            <input type="text" class="form-control" id="db_user" name="db_user" 
                                   value="<?php echo htmlspecialchars($_POST['db_user'] ?? ''); ?>" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="db_pass" class="form-label">Database Password</label>
                            <input type="password" class="form-control" id="db_pass" name="db_pass">
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-lg w-100">
                            <i class="fas fa-arrow-right me-2"></i>Test Connection & Continue
                        </button>
                    </form>

                <?php elseif ($step == 2): ?>
                    <!-- Step 2: Import Database -->
                    <h3><i class="fas fa-download me-2"></i>Import Database</h3>
                    <p class="text-muted mb-4">Import the database schema and sample data.</p>
                    
                    <form method="POST">
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="import_sample_data" name="import_sample_data" checked>
                            <label class="form-check-label" for="import_sample_data">
                                Import sample data (recommended for testing)
                            </label>
                        </div>
                        
                        <div class="alert alert-info">
                            <i class="fas fa-info-circle me-2"></i>
                            This will create all necessary database tables and import sample content.
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-lg w-100">
                            <i class="fas fa-database me-2"></i>Import Database
                        </button>
                    </form>

                <?php elseif ($step == 3): ?>
                    <!-- Step 3: Create Admin User -->
                    <h3><i class="fas fa-user-shield me-2"></i>Create Admin User</h3>
                    <p class="text-muted mb-4">Create your administrator account.</p>
                    
                    <form method="POST">
                        <div class="mb-3">
                            <label for="admin_name" class="form-label">Full Name</label>
                            <input type="text" class="form-control" id="admin_name" name="admin_name" 
                                   value="<?php echo htmlspecialchars($_POST['admin_name'] ?? ''); ?>" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="admin_email" class="form-label">Email Address</label>
                            <input type="email" class="form-control" id="admin_email" name="admin_email" 
                                   value="<?php echo htmlspecialchars($_POST['admin_email'] ?? ''); ?>" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="admin_password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="admin_password" name="admin_password" required>
                            <small class="text-muted">Minimum 6 characters</small>
                        </div>
                        
                        <div class="mb-3">
                            <label for="confirm_password" class="form-label">Confirm Password</label>
                            <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-lg w-100">
                            <i class="fas fa-user-plus me-2"></i>Create Admin User
                        </button>
                    </form>

                <?php elseif ($step == 4): ?>
                    <!-- Step 4: Site Configuration -->
                    <h3><i class="fas fa-cog me-2"></i>Site Configuration</h3>
                    <p class="text-muted mb-4">Configure your site settings.</p>
                    
                    <form method="POST">
                        <div class="mb-3">
                            <label for="site_title" class="form-label">Site Title</label>
                            <input type="text" class="form-control" id="site_title" name="site_title" 
                                   value="<?php echo htmlspecialchars($_POST['site_title'] ?? 'GeoPortfolio Pro'); ?>">
                        </div>
                        
                        <div class="mb-3">
                            <label for="site_description" class="form-label">Site Description</label>
                            <textarea class="form-control" id="site_description" name="site_description" rows="3"><?php echo htmlspecialchars($_POST['site_description'] ?? 'A modern portfolio for GIS & Remote Sensing professionals'); ?></textarea>
                        </div>
                        
                        <div class="mb-3">
                            <label for="copyright_text" class="form-label">Copyright Text</label>
                            <input type="text" class="form-control" id="copyright_text" name="copyright_text" 
                                   value="<?php echo htmlspecialchars($_POST['copyright_text'] ?? 'GeoPortfolio Pro. All rights reserved.'); ?>">
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-lg w-100">
                            <i class="fas fa-save me-2"></i>Save Configuration
                        </button>
                    </form>

                <?php elseif ($step == 5): ?>
                    <!-- Step 5: Installation Complete -->
                    <div class="text-center">
                        <i class="fas fa-check-circle fa-5x text-success mb-4"></i>
                        <h3>Installation Complete!</h3>
                        <p class="text-muted mb-4">GeoPortfolio Pro has been successfully installed.</p>
                        
                        <div class="row mb-4">
                            <div class="col-md-6 mb-3">
                                <div class="card">
                                    <div class="card-body text-center">
                                        <i class="fas fa-home fa-2x text-primary mb-2"></i>
                                        <h6>Visit Your Site</h6>
                                        <a href="index.php" class="btn btn-outline-primary">Go to Homepage</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <div class="card">
                                    <div class="card-body text-center">
                                        <i class="fas fa-cog fa-2x text-success mb-2"></i>
                                        <h6>Admin Panel</h6>
                                        <a href="admin/" class="btn btn-outline-success">Go to Admin</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="alert alert-warning">
                            <i class="fas fa-exclamation-triangle me-2"></i>
                            <strong>Important:</strong> For security reasons, please delete the <code>install.php</code> file after installation.
                        </div>
                        
                        <div class="alert alert-info">
                            <i class="fas fa-info-circle me-2"></i>
                            You can now log in to the admin panel with the credentials you created.
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>